config/routes.rb
Rails.application.routes.draw do
  resources :child_notes
  resources :families
  resources :children
  resources :hosting_session_spot_children
  resources :spot_statuses
  resources :hosting_session_spots
  resources :hosting_sessions
  get 'public/children/:id', to: 'public#children'
  get 'public/child/:id', to: 'public#child'

  root to: 'dashboards#index'

  # All routes
  get "dashboards/dashboard_4"
  get "dashboards/index"
  get "dashboards/children"
  get "dashboards/children2"
  get "dashboards/child"
  get "dashboards/child_adminview"
  get "dashboards/register"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/spot_statuses_controller.rb
class SpotStatusesController < ApplicationController
  before_action :set_spot_status, only: [:show, :edit, :update, :destroy]

  # GET /spot_statuses
  def index
    @spot_statuses = SpotStatus.all
  end

  # GET /spot_statuses/1
  def show
  end

  # GET /spot_statuses/new
  def new
    @spot_status = SpotStatus.new
  end

  # GET /spot_statuses/1/edit
  def edit
  end

  # POST /spot_statuses
  def create
    @spot_status = SpotStatus.new(spot_status_params)

    if @spot_status.save
      redirect_to @spot_status, notice: 'Spot status was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /spot_statuses/1
  def update
    if @spot_status.update(spot_status_params)
      redirect_to @spot_status, notice: 'Spot status was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /spot_statuses/1
  def destroy
    @spot_status.destroy
    redirect_to spot_statuses_url, notice: 'Spot status was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot_status
      @spot_status = SpotStatus.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def spot_status_params
      params.require(:spot_status).permit(:name, :public)
    end
end

app/helpers/spot_statuses_helper.rb
module SpotStatusesHelper
end

app/views/spot_statuses/_form.html.erb
<%= bootstrap_form_for( @spot_status, layout: :horizontal ) do |form| %>
  <% if spot_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spot_status.errors.count, "error") %> prohibited this spot_status from being saved:</h2>

      <ul>
      <% spot_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
                <%= form.text_field :name, id: :spot_status_name %>
            </div>

    <div class="field">
                <%= form.check_box :public, id: :spot_status_public %>
            </div>

    <div class="btn">
        <%= form.submit class: 'btn btn-sm btn-outline dim btn-success' do %>
            <i class="fa fa-chevron-left"></i> Submit
        <% end %>
    </div>
<% end %>

app/views/spot_statuses/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h1>Editing Spot Status</h1>
            </div>
            <div class="ibox-content">
                <%= render 'form', spot_status: @spot_status %>

                <hr>
                <div class="btn">
                    <%= link_to spot_statuses_path, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-chevron-left"></i> Back
                    <% end %>
                    <%= link_to @spot_status, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-search"></i> Show
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/spot_statuses/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Spot Statuses </h5>
            </div>
            <div class="ibox-content">

                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Public</th>
                                                <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        <% @spot_statuses.each do |spot_status| %>
                        <tr>
                            <td><%= spot_status.name %></td>
                            <td><%= spot_status.public %></td>
                                                        <td>
                                <div class="btn-group">
                                    <%= link_to spot_status, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                                        <i class="fa fa-search"></i>
                                    <% end %>
                                    <%= link_to edit_spot_status_path(spot_status), class: 'btn btn-sm btn-outline dim btn-info' do %>
                                        <i class="fa fa-edit"></i>
                                    <% end %>
                                    <%= link_to spot_status, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline dim btn-danger' do %>
                                        <i class="fa fa-trash-o"></i>
                                    <% end %>
                                </div>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                <hr>
                <div class="btn">
                    <%= link_to new_spot_status_path, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-plus"></i> New Spot Status
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/spot_statuses/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h1>New Spot Status</h1>
            </div>
            <div class="ibox-content">
                <%= render 'form', spot_status: @spot_status %>

                <hr>
                <div class="btn">
                    <%= link_to spot_statuses_path, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-chevron-left"></i> Back
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/spot_statuses/show.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Spot Statuses ID #<%= @spot_status.id %></h5>
            </div>
            <div class="ibox-content">
                                <p>
                    <strong>Name:</strong>
                    <%= @spot_status.name %>
                </p>

                                <p>
                    <strong>Public:</strong>
                    <%= @spot_status.public %>
                </p>

                                
                <hr>
                <div class="btn">
                    <%= link_to spot_statuses_path, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-chevron-left"></i> Back
                    <% end %>
                    <%= link_to edit_spot_status_path(@spot_status), class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-edit"></i> Edit Spot Status
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>