config/routes.rb
Rails.application.routes.draw do
  resources :child_notes
  resources :families
  resources :children
  resources :hosting_session_spot_children
  resources :spot_statuses
  resources :hosting_session_spots
  resources :hosting_sessions
  get 'public/children/:id', to: 'public#children'
  get 'public/child/:id', to: 'public#child'

  root to: 'dashboards#index'

  # All routes
  get "dashboards/dashboard_4"
  get "dashboards/index"
  get "dashboards/children"
  get "dashboards/children2"
  get "dashboards/child"
  get "dashboards/child_adminview"
  get "dashboards/register"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hosting_session_spot.rb
class HostingSessionSpot < ApplicationRecord
  belongs_to :hosting_session
  has_many :hosting_session_spot_children
  has_many :children, :through => :hosting_session_spot_children
  belongs_to :family, optional: true
  belongs_to :status, :class_name => 'SpotStatus'
  
  scope :on_hold, -> { where(status: SpotStatus.find_by_name('On-Hold'))}
  scope :hosted, -> { where(status: SpotStatus.find_by_name('Hosted'))}
  scope :available, -> { where(status: SpotStatus.find_by_name('Available'))}
  
  
  def public_name
    children.map{|child| child.public_name}.join ', '
  end
  
  def country
    children.first.country
  end
  
  def public_photos
    @files = []
    children.each do |child|
      @files << ChildFile.where(child_id: child.id).where(type: 'image/jpeg').where(public: true)
    end
    @files.flatten
  end

  def public_notes
    @notes = []
    children.each do |child|
      @notes << ChildNote.where(child_id: child.id).where(public: true)
    end
    @notes.flatten
  end

end

app/controllers/hosting_session_spots_controller.rb
class HostingSessionSpotsController < ApplicationController
  before_action :set_hosting_session_spot, only: [:show, :edit, :update, :destroy]

  # GET /hosting_session_spots
  def index
    @hosting_session_spots = HostingSessionSpot.all
  end

  # GET /hosting_session_spots/1
  def show
  end

  # GET /hosting_session_spots/new
  def new
    @hosting_session_spot = HostingSessionSpot.new
  end

  # GET /hosting_session_spots/1/edit
  def edit
  end

  # POST /hosting_session_spots
  def create
    @hosting_session_spot = HostingSessionSpot.new(hosting_session_spot_params)

    if @hosting_session_spot.save
      redirect_to @hosting_session_spot, notice: 'Hosting session spot was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /hosting_session_spots/1
  def update
    if @hosting_session_spot.update(hosting_session_spot_params)
      redirect_to @hosting_session_spot, notice: 'Hosting session spot was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /hosting_session_spots/1
  def destroy
    @hosting_session_spot.destroy
    redirect_to hosting_session_spots_url, notice: 'Hosting session spot was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hosting_session_spot
      @hosting_session_spot = HostingSessionSpot.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def hosting_session_spot_params
      params.require(:hosting_session_spot).permit(:status_id, :hosting_session_id, :description, :scholarship, :family_id)
    end
end

app/helpers/hosting_session_spots_helper.rb
module HostingSessionSpotsHelper
end

app/views/hosting_session_spots/_form.html.erb
<%= bootstrap_form_for( @hosting_session_spot, layout: :horizontal ) do |form| %>
  <% if hosting_session_spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hosting_session_spot.errors.count, "error") %> prohibited this hosting_session_spot from being saved:</h2>

      <ul>
      <% hosting_session_spot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
                <%= form.number_field :status_id, id: :hosting_session_spot_status_id %>
            </div>

    <div class="field">
                <%= form.number_field :hosting_session_id, id: :hosting_session_spot_hosting_session_id %>
            </div>

    <div class="field">
                <%= form.text_area :description, id: :hosting_session_spot_description %>
            </div>

    <div class="field">
                <%= form.number_field :scholarship, id: :hosting_session_spot_scholarship %>
            </div>

    <div class="field">
                <%= form.number_field :family_id, id: :hosting_session_spot_family_id %>
            </div>

    <div class="btn">
        <%= form.submit class: 'btn btn-sm btn-outline dim btn-success' do %>
            <i class="fa fa-chevron-left"></i> Submit
        <% end %>
    </div>
<% end %>

app/views/hosting_session_spots/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h1>Editing Hosting Session Spot</h1>
            </div>
            <div class="ibox-content">
                <%= render 'form', hosting_session_spot: @hosting_session_spot %>

                <hr>
                <div class="btn">
                    <%= link_to hosting_session_spots_path, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-chevron-left"></i> Back
                    <% end %>
                    <%= link_to @hosting_session_spot, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-search"></i> Show
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/hosting_session_spots/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Hosting Session Spots </h5>
            </div>
            <div class="ibox-content">

                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Children</th>
                        <th>Status</th>
                        <th>Hosting session</th>
                        <th>Description</th>
                        <th>Scholarship</th>
                        <th>Family</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        <% @hosting_session_spots.each do |hosting_session_spot| %>
                        <tr>
                            <td>
                                <% hosting_session_spot.children.each do |child| %>
                                <%= child.identifier %>: <%= child.full_name %><br/>
                                <% end %>
                            </td>
                            <td><%= hosting_session_spot.status.name %></td>
                            <td><%= hosting_session_spot.hosting_session.name %></td>
                            <td><%= hosting_session_spot.description %></td>
                            <td><%= hosting_session_spot.scholarship %></td>
                            <td><%= hosting_session_spot.family&.short_name %></td>
                                                        <td>
                                <div class="btn-group">
                                    <%= link_to hosting_session_spot, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                                        <i class="fa fa-search"></i>
                                    <% end %>
                                    <%= link_to edit_hosting_session_spot_path(hosting_session_spot), class: 'btn btn-sm btn-outline dim btn-info' do %>
                                        <i class="fa fa-edit"></i>
                                    <% end %>
                                    <%= link_to hosting_session_spot, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline dim btn-danger' do %>
                                        <i class="fa fa-trash-o"></i>
                                    <% end %>
                                </div>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                <hr>
                <div class="btn">
                    <%= link_to new_hosting_session_spot_path, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-plus"></i> New Hosting Session Spot
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/hosting_session_spots/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h1>New Hosting Session Spot</h1>
            </div>
            <div class="ibox-content">
                <%= render 'form', hosting_session_spot: @hosting_session_spot %>

                <hr>
                <div class="btn">
                    <%= link_to hosting_session_spots_path, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-chevron-left"></i> Back
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/hosting_session_spots/show.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Hosting Session Spots ID #<%= @hosting_session_spot.id %></h5>
            </div>
            <div class="ibox-content">
                                <p>
                    <strong>Status:</strong>
                    <%= @hosting_session_spot.status_id %>
                </p>

                                <p>
                    <strong>Hosting session:</strong>
                    <%= @hosting_session_spot.hosting_session_id %>
                </p>

                                <p>
                    <strong>Description:</strong>
                    <%= @hosting_session_spot.description %>
                </p>

                                <p>
                    <strong>Scholarship:</strong>
                    <%= @hosting_session_spot.scholarship %>
                </p>

                                <p>
                    <strong>Family:</strong>
                    <%= @hosting_session_spot.family_id %>
                </p>

                                
                <hr>
                <div class="btn">
                    <%= link_to hosting_session_spots_path, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-chevron-left"></i> Back
                    <% end %>
                    <%= link_to edit_hosting_session_spot_path(@hosting_session_spot), class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-edit"></i> Edit Hosting Session Spot
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>