config/routes.rb
Rails.application.routes.draw do
  resources :child_notes
  resources :families
  resources :children
  resources :hosting_session_spot_children
  resources :spot_statuses
  resources :hosting_session_spots
  resources :hosting_sessions
  get 'public/children/:id', to: 'public#children'
  get 'public/child/:id', to: 'public#child'

  root to: 'dashboards#index'

  # All routes
  get "dashboards/dashboard_4"
  get "dashboards/index"
  get "dashboards/children"
  get "dashboards/children2"
  get "dashboards/child"
  get "dashboards/child_adminview"
  get "dashboards/register"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hosting_session.rb
class HostingSession < ApplicationRecord
  has_many :hosting_session_spots
  has_many :children, :through => :hosting_session_spots
end

app/controllers/hosting_sessions_controller.rb
class HostingSessionsController < ApplicationController
  before_action :set_hosting_session, only: [:show, :edit, :update, :destroy]

  # GET /hosting_sessions
  def index
    @hosting_sessions = HostingSession.all
  end

  # GET /hosting_sessions/1
  def show
  end

  # GET /hosting_sessions/new
  def new
    @hosting_session = HostingSession.new
  end

  # GET /hosting_sessions/1/edit
  def edit
  end

  # POST /hosting_sessions
  def create
    @hosting_session = HostingSession.new(hosting_session_params)

    if @hosting_session.save
      redirect_to @hosting_session, notice: 'Hosting session was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /hosting_sessions/1
  def update
    if @hosting_session.update(hosting_session_params)
      redirect_to @hosting_session, notice: 'Hosting session was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /hosting_sessions/1
  def destroy
    @hosting_session.destroy
    redirect_to hosting_sessions_url, notice: 'Hosting session was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hosting_session
      @hosting_session = HostingSession.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def hosting_session_params
      params.require(:hosting_session).permit(:name, :date, :public)
    end
end

app/helpers/hosting_sessions_helper.rb
module HostingSessionsHelper
end

app/views/hosting_sessions/_form.html.erb
<%= bootstrap_form_for( @hosting_session, layout: :horizontal ) do |form| %>
  <% if hosting_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hosting_session.errors.count, "error") %> prohibited this hosting_session from being saved:</h2>

      <ul>
      <% hosting_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
                <%= form.text_field :name, id: :hosting_session_name %>
            </div>

    <div class="field">
                <%= form.date_select :date, id: :hosting_session_date %>
            </div>

    <div class="field">
                <%= form.check_box :public, id: :hosting_session_public %>
            </div>

    <div class="btn">
        <%= form.submit class: 'btn btn-sm btn-outline dim btn-success' do %>
            <i class="fa fa-chevron-left"></i> Submit
        <% end %>
    </div>
<% end %>

app/views/hosting_sessions/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h1>Editing Hosting Session</h1>
            </div>
            <div class="ibox-content">
                <%= render 'form', hosting_session: @hosting_session %>

                <hr>
                <div class="btn">
                    <%= link_to hosting_sessions_path, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-chevron-left"></i> Back
                    <% end %>
                    <%= link_to @hosting_session, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-search"></i> Show
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/hosting_sessions/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Hosting Sessions </h5>
            </div>
            <div class="ibox-content">

                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Date</th>
                        <th>Public</th>
                        <th>Participents</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        <% @hosting_sessions.each do |hosting_session| %>
                        <tr>
                            <td><%= hosting_session.name %></td>
                            <td><%= hosting_session.date %></td>
                            <td><%= hosting_session.public %></td>
                            <td>
                                <%= hosting_session.hosting_session_spots.count %> Session Spots / <%= hosting_session.children.count %> Children<br/>
                                <%= hosting_session.hosting_session_spots.on_hold.count %> On-Hold /  <%= hosting_session.hosting_session_spots.hosted.count %> Hosted /  <%= hosting_session.hosting_session_spots.available.count %> Available
                            </td>
                            <td>
                                <div class="btn-group">
                                    <%= link_to hosting_session, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                                        <i class="fa fa-search"></i>
                                    <% end %>
                                    <%= link_to edit_hosting_session_path(hosting_session), class: 'btn btn-sm btn-outline dim btn-info' do %>
                                        <i class="fa fa-edit"></i>
                                    <% end %>
                                    <%= link_to hosting_session, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline dim btn-danger' do %>
                                        <i class="fa fa-trash-o"></i>
                                    <% end %>
                                </div>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                <hr>
                <div class="btn">
                    <%= link_to new_hosting_session_path, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-plus"></i> New Hosting Session
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/hosting_sessions/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h1>New Hosting Session</h1>
            </div>
            <div class="ibox-content">
                <%= render 'form', hosting_session: @hosting_session %>

                <hr>
                <div class="btn">
                    <%= link_to hosting_sessions_path, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-chevron-left"></i> Back
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/hosting_sessions/show.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Hosting Sessions ID #<%= @hosting_session.id %></h5>
            </div>
            <div class="ibox-content">
                                <p>
                    <strong>Name:</strong>
                    <%= @hosting_session.name %>
                </p>

                                <p>
                    <strong>Date:</strong>
                    <%= @hosting_session.date %>
                </p>

                                <p>
                    <strong>Public:</strong>
                    <%= @hosting_session.public %>
                </p>

                                
                <hr>
                <div class="btn">
                    <%= link_to hosting_sessions_path, class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-chevron-left"></i> Back
                    <% end %>
                    <%= link_to edit_hosting_session_path(@hosting_session), class: 'btn btn-sm btn-outline dim btn-primary' do %>
                        <i class="fa fa-edit"></i> Edit Hosting Session
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>