config/routes.rb
Rails.application.routes.draw do
  resources :child_notes
  resources :families
  resources :children
  resources :hosting_session_spot_children
  resources :spot_statuses
  resources :hosting_session_spots
  resources :hosting_sessions
  get 'public/children/:id', to: 'public#children'
  get 'public/child/:id', to: 'public#child'

  root to: 'dashboards#index'

  # All routes
  get "dashboards/dashboard_4"
  get "dashboards/index"
  get "dashboards/children"
  get "dashboards/children2"
  get "dashboards/child"
  get "dashboards/child_adminview"
  get "dashboards/register"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        Example text
    </div>
    <div>
        <strong>Copyright</strong> Example Company &copy; 2014-2015
    </div>
</div>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom white-bg">
    <nav class="navbar navbar-static-top" role="navigation">
        <div class="navbar-header">
            <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                <i class="fa fa-reorder"></i>
            </button>
            
            <a href="/" class="navbar-brand">OHHC Children</a>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Sample Pages<span class="caret"></span></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><%= link_to 'Register', dashboards_register_path %></li>
                        <li><%= link_to 'Children', dashboards_children2_path %></li>
                        <li><%= link_to 'Individual Child', dashboards_child_path %></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Public<span class="caret"></span></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><%= link_to 'Winter Session', controller: 'public', action: 'children', id: 1 %></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Administrative<span class="caret"></span></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><%= link_to 'Hosting Sessions', hosting_sessions_path %></li>
                        <li><%= link_to 'Hosting Session Spots', hosting_session_spots_path %></li>
                        <li><%= link_to 'Children', children_path %></li>
                        <li><%= link_to 'Child Notes', child_notes_path %></li>
                        <li><%= link_to 'Families', families_path %></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <%= link_to dashboards_register_path do %>
                        <i class="fa fa-sign-out"></i> Log out (your@emailaddress.com)
                    <% end %>
                </li>
            </ul>
        </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OHHC Children - <%= yield :page_title %></title>

    <!-- Include style per-controller - vendor plugins -->
    <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>



</head>
<body class="top-navigation">

    <div id="modal"></div>
    <!-- Wrapper-->
    <div id="wrapper" class="<%= params[:controller] %>.<%= params[:action] %>">

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg <%= @extra_class %>">

            <!-- Page wrapper -->
            <%= render 'layouts/topnavbar' %>


            <!-- Notification alerts -->
            <% if notice %>
            <div class="row">
                <div class="col-12-sm">
                    <div class="alert alert-success alert-dismissable">
                        <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                        <%= notice %>
                    </div>
                </div>
            </div>
            <% end %>


            <!-- Main view  -->
            <%= yield %>

            <!-- Footer -->
            <%= render 'layouts/footer' %>

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

    <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

    <!-- Include javascript per-view -->
    <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
    <%= yield :javascript %>

</body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OHHC Children - <%= yield :page_title %></title>

    <!-- Include style per-controller - vendor plugins -->
    <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>



</head>
<body class="gray-bg" id="register-body">

<!-- Main view  -->
<%= yield %>


    <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

    <!-- Include javascript per-view -->
    <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
    <%= yield :javascript %>

</body>
</html>

app/views/layouts/layout_2.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>INSPINIA | Responsive admin theme</title>

    <!-- Include style per-controller - vendor plugins -->
    <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>



</head>
<body class="top-navigation">

    <!-- Wrapper-->
    <div id="wrapper" class="<%= params[:controller] %>.<%= params[:action] %>">

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg <%= @extra_class %>">

            <!-- Page wrapper -->
            <%= render 'layouts/topnavbar_2' %>

            <!-- Main view  -->
            <%= yield %>

            <!-- Footer -->
            <%= render 'layouts/footer' %>

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

    <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

    <!-- Include javascript per-view -->
    <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
    <%= yield :javascript %>

</body>
</html>